[project]
name = "scipy_extensions"
description = "Extensions and samplers for scientific computing"
version = "0.1.0"
authors = [
	{ name = "Ashraf Ahmed", email = "z@ashahmed.io" }
]

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
