[project]
name = "pymc_extensions"
version = "0.1.0"
dependencies = [
    "numpy",
    "arviz",
    "pymc>=5"
]

[dependency-groups]
dev = [
    "basedpyright>0",
    "pytest>0",
    "ruff>0",
]

[tool.uv]
package = true

[tool.pyright]
venvPath = "../.."
venv = ".venv"
strict = ["**/*.py"]
pythonVersion = "3.13"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pymc_extensions"]
